### ISSUE TITLE
Possibly causing Invalid Player Data

### ISSUE THREAD

**Issue by Infestidos** [JayemCeekay/ForgeSniper#2]
Last night started using this mod on a server. Game crashed (index out of bounds, happens w/o this mod) and when trying to rejoin got "Invalid player data". Restoring my data from a backup fixed it. Today game crashed again (same cause), same issue arose. This time my backup was so old that I decided to try looking into what caused the error. Here's a snippet of the server log when I get disconnected.
[DC.txt](https://github.com/JayemCeekay/ForgeSniper/files/9176957/DC.txt)

Removing this mod allowed me to rejoin without having to restore from a backup.

**Comment by JayemCeekay** [comment]
I believe I have found the cause of the issue. It should be fixed in the hotfix I am releasing later today.

**Comment by JayemCeekay** [comment]
Can you test the latest release and let me know if this is still happening?

**Comment by Infestidos** [comment]
Yes, I don’t know how long it will take as the crash happens randomly.

**Comment by Infestidos** [comment]
Fixed
